### PR TITLE
Feature/secrets manager add on

### PR DESCRIPTION
**Pull request by askulkarni2**
*Issue #, if available:* #68

*Description of changes:* 

See review history details in https://github.com/aws-quickstart/ssp-amazon-eks/pull/133

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by kcoleman731 — DISMISSED** [review]

**Comment by jaymccon** [comment]
heads up, I manually cleaned up the stack that failed to delete. Reason for failing was a load balancer was left behind (`k8s-kubesyst-sspaddon-fa9d1244cf`). This typically happens when k8s provisions an elb and then the cluster is deleted without first deleting the LoadBalancer resource using the k8s api.

**Review by shapirov103 — APPROVED** [review]
lgtm

**Pull request merged**
