### PR TITLE
Bugfix/calico node failure

### PR DESCRIPTION
**Pull request by shapirov103**
*Issue #, if available:*

*Description of changes:* Calico node daemonset fails with OOM. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shapirov103** [comment]
may also apply to the terraform version (although could not find source for calico addon)

**Review by askulkarni2 — APPROVED** [review]
lgtm!

**Pull request merged**
